trigger:
- main

pool:
  name: Default

stages:

# ============================
# STAGE 1 : CI (Build + Test)
# ============================

- stage: CI
  displayName: Build and Push Images
  jobs:
  - job: Build
    steps:

    # -------- API Gateway --------

    - script: mvn test
      workingDirectory: api-gateway
      displayName: API Gateway - Test

    - task: Docker@2
      displayName: API Gateway - Build & Push
      inputs:
        command: buildAndPush
        containerRegistry: dockerhub
        repository: prashasthnaik/apigateway
        dockerfile: api-gateway/Dockerfile
        tags: latest


    # -------- Eureka --------

    - script: mvn test
      workingDirectory: eureka-server
      displayName: Eureka - Test

    - task: Docker@2
      displayName: Eureka - Build & Push
      inputs:
        command: buildAndPush
        containerRegistry: dockerhub
        repository: prashasthnaik/eureka
        dockerfile: eureka-server/Dockerfile
        tags: latest


    # -------- Frontend --------

    - script: |
        npm install
        npm test
      workingDirectory: frontend
      displayName: Frontend - Test

    - task: Docker@2
      displayName: Frontend - Build & Push
      inputs:
        command: buildAndPush
        containerRegistry: dockerhub
        repository: prashasthnaik/frontend
        dockerfile: frontend/Dockerfile
        tags: latest


    # -------- Order Service --------

    - script: mvn test
      workingDirectory: order-service
      displayName: Order - Test

    - task: Docker@2
      displayName: Order - Build & Push
      inputs:
        command: buildAndPush
        containerRegistry: dockerhub
        repository: prashasthnaik/order
        dockerfile: order-service/Dockerfile
        tags: latest


    # -------- Product Service --------

    - script: mvn test
      workingDirectory: product-service
      displayName: Product - Test

    - task: Docker@2
      displayName: Product - Build & Push
      inputs:
        command: buildAndPush
        containerRegistry: dockerhub
        repository: prashasthnaik/product
        dockerfile: product-service/Dockerfile
        tags: latest


    # -------- User Service --------

    - script: mvn test
      workingDirectory: user-service
      displayName: User - Test

    - task: Docker@2
      displayName: User - Build & Push
      inputs:
        command: buildAndPush
        containerRegistry: dockerhub
        repository: prashasthnaik/user
        dockerfile: user-service/Dockerfile
        tags: latest


