trigger:
- main

pool:
  name: Default

steps:

# ================= API Gateway =================

- script: mvn test
  workingDirectory: api-gateway
  displayName: API Gateway - Run Tests

- task: PublishTestResults@2
  displayName: API Gateway - Publish Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/api-gateway/target/surefire-reports/*.xml'

- task: PublishBuildArtifacts@1
  displayName: API Gateway - Save Test Reports
  inputs:
    pathToPublish: api-gateway/target
    artifactName: api-gateway-test-reports

- task: Docker@2
  displayName: API Gateway - Build & Push
  inputs:
    command: buildAndPush
    containerRegistry: dockerhub
    repository: prashasthnaik/apigateway
    dockerfile: api-gateway/Dockerfile
    tags: latest


# ================= Eureka =================

- script: mvn test
  workingDirectory: eureka-server
  displayName: Eureka - Run Tests

- task: PublishTestResults@2
  displayName: Eureka - Publish Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/eureka-server/target/surefire-reports/*.xml'

- task: PublishBuildArtifacts@1
  displayName: Eureka - Save Test Reports
  inputs:
    pathToPublish: eureka-server/target
    artifactName: eureka-test-reports

- task: Docker@2
  displayName: Eureka - Build & Push
  inputs:
    command: buildAndPush
    containerRegistry: dockerhub
    repository: prashasthnaik/eureka
    dockerfile: eureka-server/Dockerfile
    tags: latest


# ================= Frontend =================

- script: |
    npm install
    npm test
  workingDirectory: frontend
  displayName: Frontend - Build & Test

- task: PublishBuildArtifacts@1
  displayName: Frontend - Save Test Reports
  inputs:
    pathToPublish: frontend
    artifactName: frontend-test-reports

- task: Docker@2
  displayName: Frontend - Build & Push
  inputs:
    command: buildAndPush
    containerRegistry: dockerhub
    repository: prashasthnaik/frontend
    dockerfile: frontend/Dockerfile
    tags: latest


# ================= Order Service =================

- script: mvn test
  workingDirectory: order-service
  displayName: Order Service - Run Tests

- task: PublishTestResults@2
  displayName: Order Service - Publish Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/order-service/target/surefire-reports/*.xml'

- task: PublishBuildArtifacts@1
  displayName: Order Service - Save Test Reports
  inputs:
    pathToPublish: order-service/target
    artifactName: order-test-reports

- task: Docker@2
  displayName: Order Service - Build & Push
  inputs:
    command: buildAndPush
    containerRegistry: dockerhub
    repository: prashasthnaik/order
    dockerfile: order-service/Dockerfile
    tags: latest


# ================= Product Service =================

- script: mvn test
  workingDirectory: product-service
  displayName: Product Service - Run Tests

- task: PublishTestResults@2
  displayName: Product Service - Publish Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/product-service/target/surefire-reports/*.xml'

- task: PublishBuildArtifacts@1
  displayName: Product Service - Save Test Reports
  inputs:
    pathToPublish: product-service/target
    artifactName: product-test-reports

- task: Docker@2
  displayName: Product Service - Build & Push
  inputs:
    command: buildAndPush
    containerRegistry: dockerhub
    repository: prashasthnaik/product
    dockerfile: product-service/Dockerfile
    tags: latest


# ================= User Service =================

- script: mvn test
  workingDirectory: user-service
  displayName: User Service - Run Tests

- task: PublishTestResults@2
  displayName: User Service - Publish Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/user-service/target/surefire-reports/*.xml'

- task: PublishBuildArtifacts@1
  displayName: User Service - Save Test Reports
  inputs:
    pathToPublish: user-service/target
    artifactName: user-test-reports

- task: Docker@2
  displayName: User Service - Build & Push
  inputs:
    command: buildAndPush
    containerRegistry: dockerhub
    repository: prashasthnaik/user
    dockerfile: user-service/Dockerfile
    tags: latest
