apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        #image: prashasthnaik/user:latest
        image: prashasthnaik/user:$(Build.BuildId)
        imagePullPolicy: Always
        ports:
        - containerPort: 8083